[versions]
composePlugin = "1.9.3"
kotlin = "2.2.21"
kotlinxCoroutines = "1.10.2"
kotlinxSerializationJson = "1.8.1"
koin = "4.0.3"
precompose = "1.6.2"
hotReload = "1.1.0-alpha02"
slf4j = "2.0.12"
deskit = "1.4.1"

[libraries]
# Kotlinx
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlinxCoroutines" }
kotlinx-coroutines-swing = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-swing", version.ref = "kotlinxCoroutines" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }

# Koin
koin-core = { group = "io.insert-koin", name = "koin-core", version.ref = "koin" }

# PreCompose
precompose = { group = "moe.tlaster", name = "precompose", version.ref = "precompose" }

# SLF4J Logging (for hot reload)
slf4j-api = { group = "org.slf4j", name = "slf4j-api", version.ref = "slf4j" }
slf4j-simple = { group = "org.slf4j", name = "slf4j-simple", version.ref = "slf4j" }

# Deskit
deskit = { group = "com.github.zahid4kh", name = "deskit", version.ref = "deskit" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
jetbrains-compose = { id = "org.jetbrains.compose", version.ref = "composePlugin" }
kotlin-plugin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-plugin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
hotReload = { id = "org.jetbrains.compose.hot-reload", version.ref = "hotReload" }

[bundles]
slf4j = ["slf4j-api", "slf4j-simple"]